general {
    base_exp_dir = ./exp/CASE_NAME/ba_noisy_poses_intrinsics
    exp_name = CASE_NAME_ba_noisy_poses_intrinsics
    recording = [
        ./,
        ./models
    ]
}

dataset {
    data_dir = ./public_data/CASE_NAME/
    render_cameras_name = cameras_sphere.npz
    object_cameras_name = cameras_sphere.npz
    init_pose = True
    init_intrinsic = True
    learn_pose = True
    learn_intrinsic = True
    noise_magnitude = 0.1
    trans_offset = 1.5
    learn_scale = True
    learn_shift = True
    fix_scaleN = True
    num_sources = 2
    type_sources = "sequential" # method of selecting source views (mvs | sequential)
}

train {
    learning_rate = 5e-4
    learning_rate_alpha = 0.05
    end_iter = 300000

    batch_size = 512 # number of camera rays per batch (iteration)
    validate_resolution_level = 4
    warm_up_end = 5000
    anneal_end = 0
    use_white_bkgd = False

    save_freq = 10000
    val_freq = 2500
    val_mesh_freq = 5000
    report_freq = 100

    igr_weight = 0.1
    mask_weight = 0.1
    depth_weight = 0.1

    use_masked_loss = True # required for depth loss to avoid NaNs
    use_ssi_depth_loss = False # SSI changes camera parameters aggressively and causes the mesh to be oversmoothed

    phase_delim = [0.2, 0.6]
    pc_weight = [0.0, 0.1, 0.01]
    feat_weight = [0.0, 0.0, 0.0]
    depth_from_inside_only = [False, True, True]
    object_mask_type = "zero_sdf_mask"
}

model {
    nerf {
        D = 8,
        d_in = 4,
        d_in_view = 3,
        W = 256,
        multires = 10,
        multires_view = 4,
        barf_c2f = [], # C2F encoding of 3D position and view dir
        output_ch = 4,
        skips=[4],
        use_viewdirs=True
    }

    sdf_network {
        d_out = 257
        d_in = 3
        d_hidden = 256
        n_layers = 8
        skip_in = [4]
        multires = 6
        barf_c2f = [] # C2F encoding of 3D position
        bias = 0.5
        scale = 1.0 # change to 3.0 for large ROI or thin structures
        geometric_init = True
        weight_norm = True
        inside_outside = False
    }

    variance_network {
        init_val = 0.3
    }

    rendering_network {
        d_feature = 256
        mode = idr
        d_in = 9
        d_out = 3
        d_hidden = 256
        n_layers = 4
        weight_norm = True
        multires_view = 4
        barf_c2f = [] # C2F encoding of view dir
        squeeze_out = True
    }

    neus_renderer {
        n_samples = 64
        n_importance = 64
        n_outside = 0 # change to 32 for without mask
        up_sample_steps = 4  # 1 for simple coarse-to-fine sampling
        perturb = 1.0
    }
}